In [1]:
import torch
import torch.nn as nn

In [9]:
# input 
input = torch.tensor([1.0,2.0,3.0])
torch.manual_seed(42)

In [10]:
neuron = nn.Linear(in_features=3,out_features=1)

In [11]:
output = neuron(input)

In [12]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [13]:
neuron.weight


Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)

In [14]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)

In [15]:
neuron.weight@input+neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)